#!/usr/bin/env bash
set -euo pipefail

# Install a built Pixel Composer Linux VM build as a desktop application:
# application directory, launcher, .desktop entry and icon.
#
#   ./tools/linux/install.sh                  # system-wide as root, per-user otherwise
#   ./tools/linux/install.sh --user           # force a per-user installation
#   ./tools/linux/install.sh --from DIR       # install a build made elsewhere
#   ./tools/linux/install.sh --uninstall
#
# The input is the directory produced by tools/arch-linux/sandbox-build-smoke.sh
# (or tools/linux/build-in-container.sh): the compiled "assets/" payload plus
# the matching GameMaker "runner". Linux Compile alone does not produce a
# standalone application, which is why the build directory - not the project
# output zip - is what gets installed.
#
# The generated launcher carries the opt-in UI snapshot workaround
# (PXC_UI_FREEZE=1, see ARCH-LINUX.md). It is read at startup and is not a
# saved preference, so every launcher has to set it; PXC_UI_FREEZE=0 in the
# environment turns it off again.
#
# Overrides: PXC_SANDBOX_CACHE, PXC_APP_DIR, PXC_BIN_DIR, PXC_DATA_DIR.

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)"
CACHE="${PXC_SANDBOX_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/pixel-composer-arch-sandbox}"

mode=install
source_dir=""
force_user=0
skip_dep_check=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --user)         force_user=1 ;;
    --from)         source_dir="${2:-}"; shift ;;
    --app-dir)      PXC_APP_DIR="${2:-}"; shift ;;
    --bin-dir)      PXC_BIN_DIR="${2:-}"; shift ;;
    --data-dir)     PXC_DATA_DIR="${2:-}"; shift ;;
    --skip-dep-check) skip_dep_check=1 ;;
    --uninstall)    mode=uninstall ;;
    -h|--help)      sed -n '3,25p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

if [[ "$force_user" -eq 1 || "${EUID:-$(id -u)}" -ne 0 ]]; then
  app_dir="${PXC_APP_DIR:-$HOME/.local/lib/pixel-composer}"
  bin_dir="${PXC_BIN_DIR:-$HOME/.local/bin}"
  data_dir="${PXC_DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}}"
else
  app_dir="${PXC_APP_DIR:-/opt/pixel-composer}"
  bin_dir="${PXC_BIN_DIR:-/usr/local/bin}"
  data_dir="${PXC_DATA_DIR:-/usr/local/share}"
fi

launcher="$bin_dir/pixel-composer"
desktop_file="$data_dir/applications/pixel-composer.desktop"
icon_file="$data_dir/icons/hicolor/256x256/apps/pixel-composer.png"

refresh_caches() {
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$data_dir/applications" 2>/dev/null || true
  fi
  if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -qtf "$data_dir/icons/hicolor" 2>/dev/null || true
  fi
}

if [[ "$mode" == uninstall ]]; then
  rm -rf "$app_dir"
  rm -f "$launcher" "$desktop_file" "$icon_file"
  refresh_caches
  echo "Removed $app_dir, $launcher, $desktop_file and the installed icon."
  exit 0
fi

[[ -n "$source_dir" ]] || source_dir="$CACHE/vm-build"
if [[ ! -s "$source_dir/assets/game.unx" || ! -f "$source_dir/runner" ]]; then
  echo "error: no usable build in $source_dir" >&2
  echo "       expected assets/game.unx and the GameMaker runner next to it." >&2
  echo "       Build first: ./tools/linux/build-in-container.sh" >&2
  exit 1
fi

# Swap the directory into place instead of copying over a running installation.
staging="$app_dir.new.$$"
rm -rf "$staging"
mkdir -p "$(dirname "$app_dir")" "$bin_dir" "$data_dir/applications"
cp -a "$source_dir" "$staging"
chmod +x "$staging/runner"

previous="$app_dir.old.$$"
if [[ -d "$app_dir" ]]; then
  mv "$app_dir" "$previous"
fi
mv "$staging" "$app_dir"
rm -rf "$previous"

cat > "$launcher" <<LAUNCHER
#!/bin/sh
# Pixel Composer launcher, generated by tools/linux/install.sh.
#
# PXC_UI_FREEZE=1 enables the confirmed Linux UI snapshot workaround against
# menu/panel flicker during node rendering (ARCH-LINUX.md). It is read at
# startup, not stored in preferences, so it has to be set on every launch.
# Set PXC_UI_FREEZE=0 to compare against the unmodified drawing path.
set -eu

APP="\${PXC_APP_DIR:-$app_dir}"
if [ ! -x "\$APP/runner" ]; then
    echo "Pixel Composer is not installed (\$APP/runner is missing)." >&2
    exit 1
fi

cd "\$APP"
unset PXC_UI_STATE_RESET
PXC_UI_FREEZE="\${PXC_UI_FREEZE:-1}"
export PXC_UI_FREEZE
exec ./runner "\$@"
LAUNCHER
chmod 0755 "$launcher"

icon_source="$(find "$ROOT/sprites/s_icon_256" -maxdepth 1 -name '*.png' -print -quit 2>/dev/null || true)"
if [[ -n "$icon_source" ]]; then
  install -D -m 0644 "$icon_source" "$icon_file"
else
  echo "note: no icon found below sprites/s_icon_256, installing without one." >&2
fi

sed "s#@LAUNCHER@#$launcher#g" "$ROOT/tools/linux/pixel-composer.desktop.in" > "$desktop_file"
chmod 0644 "$desktop_file"
if command -v desktop-file-validate >/dev/null 2>&1; then
  desktop-file-validate "$desktop_file"
fi
refresh_caches

echo "Installed:"
echo "  application $app_dir"
echo "  launcher    $launcher"
echo "  menu entry  $desktop_file"
[[ -n "$icon_source" ]] && echo "  icon        $icon_file"

# The runner is dynamically linked against libraries that a build container has
# but a fresh desktop may not - missing libGLU aborts the start with
# "error while loading shared libraries" and no window at all.
if [[ "$skip_dep_check" -eq 0 ]] && command -v ldd >/dev/null 2>&1; then
  missing="$(ldd "$app_dir/runner" 2>/dev/null | awk '/not found/ {print $1}' | sort -u)"
  if [[ -n "$missing" ]]; then
    echo
    echo "error: the runner is missing shared libraries:" >&2
    printf '  %s\n' $missing >&2
    echo "       Arch:   sudo pacman -S --needed glu openal libpulse" >&2
    echo "       Debian: sudo apt install libglu1-mesa libopenal1 libpulse0" >&2
    exit 1
  fi
fi

echo
echo "Start it from the desktop menu (Pixel Composer) or with: $launcher"
if [[ ":$PATH:" != *":$bin_dir:"* ]]; then
  echo "note: $bin_dir is not in PATH."
fi
